---
#############################################
# Tasks file for the role Processing Server #
#############################################

- name: Create necessary directories
  file: path={{ item.dir }} state=directory
  with_items:
    - {dir: '{{ sw_path }}'}
#   - {dir: '{{ data_dir }}/HiSeq_X_data/nosync/archived'}
#   - {dir: '{{ data_dir }}/miseq_data/nosync/archived'}

- name: Copy configuration files for different services
  template: src={{ item.template }} dest={{ item.dest_dir }}/{{ item.dest }}
  with_items:
    - {template: 'supervisord.j2', dest_dir: '/home/{{ user }}/config', dest: 'supervisord.conf'}
    - {template: 'taca.yaml.j2', dest_dir: '/home/{{ user }}/.taca', dest: 'taca.yaml'}

#Sets host unique start times.
- set_fact:
    minutes: "{{ 10 * timing }}"

- name: Start taca cronjobs
  cron: minute={{ item.min }} hour={{ item.hour }} job={{ item.job }}
  with_items:
  - { min: "{{ minutes }}", hour: "*", job: "source ~/.bash_profile && source activate taca  &> /dev/null && taca analysis demultiplex --force"}
  - { min: "{{ minutes }}", hour: "*", job: "source ~/.bash_profile && source activate taca &> /dev/null  && taca bioinfo_deliveries update"}
  - { min: "{{ minutes }}", hour: "10", job: "source ~/.bash_profile && source activate taca &> /dev/null && taca server_status cronjobs"}
