---
#############################################
# Tasks file for the role Processing Server #
#############################################

#- name: Create necessary directories
#  file: path={{ item.dir }} state=directory 
#  with_items:
#   - {dir: '{{ data_dir }}/HiSeq_X_data/nosync/archived'}
#   - {dir: '{{ data_dir }}/miseq_data/nosync/archived'}

- name: Copy configuration files for different services
  template: src={{ item.template }} dest={{ item.dest_dir }}/{{ item.dest }}
  with_items:
    - {template: 'supervisord.j2', dest_dir: '/home/{{ user }}/config', dest: 'supervisord.conf'}
    - {template: 'taca.yaml.j2', dest_dir: '/home/{{ user }}/.taca', dest: 'taca.yaml'}

#Sets host unique start times.
- set_fact:
    minutes: "{{ 10 * timing }}"

- name: Start taca cronjobs
  cron: minute={{ item.min }} hour={{ item.hour }} job={{ item.job }} name={{ item.name }}
  with_items:
  - { min: "{{ minutes }}", hour: "*", job: "source {{ paths_file }} && source activate master  &> /dev/null && taca analysis demultiplex --force  &> /dev/null", name: "Demux & HPC transfer"}
  - { min: "{{ minutes }}", hour: "*", job: "source {{ paths_file }} && source activate master &> /dev/null  && taca bioinfo_deliveries update  &> /dev/null", name: "G-Stats delivery page updates"}
  - { min: "{{ minutes }}", hour: "10", job: "source {{ paths_file }} && source activate master &> /dev/null && taca server_status cronjobs  &> /dev/null", name: "G-Stats cronjob tracker updates"}
  - { min: "{{ minutes }}", hour: "6,16", job: "source {{ paths_file }} && source activate master &> /dev/null && taca server_status nases --statusdb &> /dev/null", name: "NAS disc usage"}

- name: Manually start supervisord process
  shell: "{{ venv_bin }}/supervisord -c /home/{{ user }}/config/supervisord.conf"
