#########################################################################
# Playbook to deploy a new processing server in NGI production platform #
#########################################################################

---
- hosts: processing
  # Switch to the production user in the Processing server for all tasks to be executed
  sudo_user: '{{ user }}'
  sudo: yes

  roles:
    - {role: miniconda, tags: MiniConda }
    - {role: bcl2fastq, tags: Bcl2Fastq }
    - {role: taca, tags: TACA }
    - {role: processing, tags: Processing-specific }
