#########################################################################
# Playbook to deploy a new processing server in NGI production platform #
#########################################################################

---
#Runs on the servers defined in [processing]
- hosts: processing
  # Switch to the production user in the Processing server for all tasks to be executed
  become: true
  become_user: "{{ user }}"

  roles:
    - {role: miniconda, tags: MiniConda }
    - {role: common, tags: Common-dependencies }
    - {role: processing, tags: Processing-specific }
    - {role: bcl2fastq, tags: Bcl2Fastq }
    - {role: taca, tags: TACA }
    - {role: longranger, tags: longranger }
