#########################################################################
# Playbook to deploy a new processing server in NGI production platform #
#########################################################################

---
#Runs on the servers defined in [processing]
- hosts: processing
  # Switch to the production user in the Processing server for all tasks to be executed
  sudo_user: '{{ user }}'
  sudo: yes
#  become_user: '{{ user }}'
#  become_method: 'sudo'

  roles:
    - {role: common, tags: Common-dependencies }
    - {role: processing, tags: Processing-specific }
    - {role: miniconda, tags: MiniConda }
    - {role: bcl2fastq, tags: Bcl2Fastq }
    - {role: taca, tags: TACA }
