- name: Create ssh-key if it does not exist yet
  user: name="{{ user }}" generate_ssh_key=yes ssh_key_bits=2048


- name: Create necessary directories
  file: path={{ item.dir }} state=directory mode=g+rwxs
  with_items:
    - {dir: '{{ sw_path }}'}
    - {dir: '/home/{{ user }}/config'}
    - {dir: '/home/{{ user }}/log'}
    - {dir: '/home/{{ user }}/.taca'}

- name: Copy configuration files for different services
  template: src={{ item.template }} dest={{ item.dest_dir }}/{{ item.dest }}
  with_items:
    - {template: 'bash_profile.j2', dest_dir: '/home/{{ user }}', dest: '.bash_profile'}

- name: Cronjob for supervisord
  cron: name="Start supervisord on reboot" special_time=reboot
        job="/usr/bin/supervisord -c /home/{{ user }}/config/supervisord.conf"
