- name: Download bcl2fastq
  get_url:
    url="{{ bcl2fastq_url }}/{{ bcl2fastq_package }}.zip"
    dest="/tmp/"

- name: Unzip bcl2fastq package
  unarchive:
    src: "/tmp/{{ bcl2fastq_package }}.zip"
    dest: "/tmp/"
    copy: no

- name: Extract bcl2fastq RPM
  shell: rpm2cpio "{{ bcl2fastq_package }}.rpm" | cpio -idmv
  args:  
    chdir: "/tmp/"

- name: Move RPM subset to Install directory
  command: mv "/tmp/usr/local/" "{{ bcl2fastq_install_dir }}" creates="/tmp/usr/local/" removes="{{ bcl2fastq_install_dir }}"

- name: Add bcl2fastq to $PATH
  lineinfile: dest="/home/{{ user }}/.bash_profile"
              line='export PATH=$PATH:{{ bcl2fastq_install_dir }}/bin'
              backup=no
