---
###############################
# Tasks file for the role NAS #
###############################

- name: Create directories if they don't not exist
  file: path={{ item.dir }} state=directory
  with_items:
    - {dir: '/home/{{ user }}/.irods'}
    - {dir: '{{ data_dir }}/hiseq_data/Runs/nosync/'}
    - {dir: '{{ data_dir }}/miseq_data/nosync/'}

#TODO: Check the validity of all of these config files
- name: Copy configuration files for different services (logrotate, lsyncd, etc.)
  template: src={{ item.template }} dest={{ item.dest_dir }}/{{ item.dest }}
  with_items:
    - {template: 'logrotate.j2', dest_dir: '/home/{{ user }}/config', dest: 'logrotate.conf'}
    - {template: 'lsyncd.j2', dest_dir: '/home/{{ user }}/config', dest: 'lsyncd.conf'}
    - {template: 'supervisord.j2', dest_dir: '/home/{{ user }}/config', dest: 'supervisord.conf'}
    - {template: 'irodsEnv.j2', dest_dir: '/home/{{ user }}/.irods', dest: '.irodsEnv'}

 name: Start NAS cronjobs
  cron: minute={{ item.min }} day={{ item.day }} hour={{ item.hour }} job={{ item.job }} name={{ item.name }}
  with_items:
  - { day: "0", hour: "0", job: "source {{ paths_file }}  &> /dev/null && taca cleanup nas --hours 18  &> /dev/null", name: "Cronjob to cleanup"}
  - { day: "0", hour: "1", job: "source {{ paths_file }}  &> /dev/null && taca backup encrypt  &> /dev/null", name: "Encrypt finished runes in nosync"}
  - { day: "0/15", job: "source /srv/mfs/configs/scripts/check_lsync.sh &> /dev/null", name: "Check lsyncd status"}

#- name: Cronjob to run logrotate
#  cron: name="Run logrotate hourly" special_time=hourly
#        job="/usr/sbin/logrotate /home/{{ user }}/config/logrotate.conf -s /home/{{ user }}/config/logrotate.status"

- name: Manually start supervisord process
  shell: "{{ venv_bin }}/supervisord -c /home/{{ user }}/config/supervisord.conf"
