---
###############################
# Tasks file for the role NAS #
###############################

- name: Create ssh-key if it does not exist yet
  user: name={{ user }} generate_ssh_key=yes ssh_key_bits=2048


- name: Create directories if they don't not exist
  file: path={{ item.dir }} state=directory
  with_items:
    - {dir: '/home/{{ user }}/config'}
    - {dir: '/home/{{ user }}/log'}
    - {dir: '/home/{{ user }}/.taca'}
    - {dir: '/home/{{ user }}/.irods'}
    - {dir: '{{ data_dir }}/hiseq_data/nosync/'}
    - {dir: '{{ data_dir }}/miseq_data/nosync/'}


- name: Copy configuration files for different services (logrotate, lsyncd, etc.)
  template: src={{ item.template }} dest={{ item.dest_dir }}/{{ item.dest }}
  with_items:
    - {template: 'logrotate.j2', dest_dir: '/home/{{ user }}/config', dest: 'logrotate.conf'}
    - {template: 'lsyncd.j2', dest_dir: '/home/{{ user }}/config', dest: 'lsyncd.conf'}
    - {template: 'supervisord.j2', dest_dir: '/home/{{ user }}/config', dest: 'supervisord.conf'}
    - {template: 'bash_profile.j2', dest_dir: '/home/{{ user }}', dest: '.bash_profile'}
    - {template: 'taca.j2', dest_dir: '/home/{{ user }}/.taca', dest: 'taca.conf'}


- name: Install code repositories from {{ code_dir }}
  shell: source $HOME/.bash_profile && cd {{ item.repo }} && python setup.py install
  args:
    chdir: "{{ code_dir }}"
  with_items: to_install
  # Some packages do not return a standard linux success code (0), but are properly installed anyway
  ignore_errors: yes


- name: Copy iRODS credentials
  template: src={{ item.template }} dest={{ item.dest_dir }}/{{ item.dest }}
  with_items:
    - {template: 'irodsEnv.j2', dest_dir: '/home/{{ user }}/.irods', dest: '.irodsEnv'}


- name: Cronjob to start supervisord
  cron: name="Start supervisord on reboot" special_time=reboot
        job="/usr/bin/supervisord -c /home/{{ user }}/config/supervisord.conf"

- name: Cronjob to run logrotate
  cron: name="Run logrotate hourly" special_time=hourly
        job="/usr/sbin/logrotate /home/{{ user }}/config/logrotate.conf -s /home/{{ user }}/config/logrotate.status"

- name: Cronjob to cleanup
  cron: name="Trigger automatic cleanup" minute="0" hour="4"
        job="0 4 * * * source ~/.bash_profile && taca storage --days 2 cleanup --site nas"

- name: Cronjob to send finished runs to swestore
  cron: name="Send HiSeq finished runs to Swestore" special_time=daily
        job="0 5 * * * source ~/.bash_profile && taca storage --days 2 archive --backend swestore"


- name: Start supervisord
  shell: /usr/bin/supervisord -c /home/{{ user }}/config/supervisord.conf
