---
###############################
# Tasks file for the role NAS #
###############################

- name: Create directories if they don't not exist
  file: path={{ item.dir }} state=directory
  with_items:
    - {dir: '/home/{{ user }}/.irods'}
    - {dir: '{{ data_dir }}/hiseq_data/Runs/nosync/'}
    - {dir: '{{ data_dir }}/miseq_data/nosync/'}

#TODO: Check the validity of all of these config files
- name: Copy configuration files for different services (logrotate, lsyncd, etc.)
  template: src={{ item.template }} dest={{ item.dest_dir }}/{{ item.dest }}
  with_items:
    - {template: 'logrotate.j2', dest_dir: '/home/{{ user }}/config', dest: 'logrotate.conf'}
    - {template: 'lsyncd.j2', dest_dir: '/home/{{ user }}/config', dest: 'lsyncd.conf'}
    - {template: 'supervisord.j2', dest_dir: '/home/{{ user }}/config', dest: 'supervisord.conf'}
    - {template: 'taca.yaml.j2', dest_dir: '/home/{{ user }}/.taca', dest: 'taca.yaml'}
    - {template: 'irodsEnv.j2', dest_dir: '/home/{{ user }}/.irods', dest: '.irodsEnv'}

#TODO: Check the validity of these cronjobs
- name: Cronjob to run logrotate
  cron: name="Run logrotate hourly" special_time=hourly
        job="/usr/sbin/logrotate /home/{{ user }}/config/logrotate.conf -s /home/{{ user }}/config/logrotate.status"

- name: Cronjob to cleanup
  cron: name="Trigger automatic cleanup" minute="0" hour="4"
        job="0 0 * * * source ~/.bashrc && taca storage --days 3 cleanup --site nas"

- name: Cronjob to send finished runs to swestore
  cron: name="Send HiSeq finished runs to Swestore" special_time=daily
        job="0 1 * * * source ~/.bashrc && taca storage --days 10 archive --backend swestore --max-runs 4"

- name: Manually start supervisord process
  shell: "{{ venv_bin }}/supervisord -c /home/{{ user }}/config/supervisord.conf"
