---
# Suffix is removed for good reason

# 2.17 implementation
#bcl2fastq_package: "bcl2fastq2-v2.17.1.14-Linux-x86_64.zip"
#bcl2fastq_url: ftp://webdata2:webdata2@ussd-ftp.illumina.com/downloads/Software/bcl2fastq/

bcl2fastq_version: "v2.19.0.316"
bcl2fastq_install_dir: "{{ sw_path }}/bcl2fastq_{{ bcl2fastq_version }}"
bcl2fastq_package: "bcl2fastq2-{{ bcl2fastq_version }}-Linux-x86_64"
bcl2fastq_url: "https://support.illumina.com/content/dam/illumina-support/documents/downloads/software/bcl2fastq/"

