---
# Suffix is removed for good reason
bcl2fastq_package: "bcl2fastq2-v2.17.1.14-Linux-x86_64"
bcl2fastq_url: ftp://webdata2:webdata2@ussd-ftp.illumina.com/downloads/Software/bcl2fastq/
bcl2fastq_install_dir: "{{ sw_path }}/bcl2fastq"
